package com.ankit.smartattendance.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF4A5EB3)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE1FF)
val LightOnPrimaryContainer = Color(0xFF00164F)
val LightSecondary = Color(0xFF5B5D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0E0F9)
val LightOnSecondaryContainer = Color(0xFF181A2C)
val LightTertiary = Color(0xFF77536C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD7F0)
val LightOnTertiaryContainer = Color(0xFF2D1127)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFEFBFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurface = Color(0xFFFEFBFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFE3E1EC)
val LightOnSurfaceVariant = Color(0xFF46464F)
val LightOutline = Color(0xFF777680)

// Dark Theme Colors
val DarkPrimary = Color(0xFFBAC3FF)
val DarkOnPrimary = Color(0xFF172E83)
val DarkPrimaryContainer = Color(0xFF32459A)
val DarkOnPrimaryContainer = Color(0xFFDEE1FF)
val DarkSecondary = Color(0xFFC4C4DD)
val DarkOnSecondary = Color(0xFF2D2F42)
val DarkSecondaryContainer = Color(0xFF434559)
val DarkOnSecondaryContainer = Color(0xFFE0E0F9)
val DarkTertiary = Color(0xFFE6BAD6)
val DarkOnTertiary = Color(0xFF45263D)
val DarkTertiaryContainer = Color(0xFF5E3C54)
val DarkOnTertiaryContainer = Color(0xFFFFD7F0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1B1B1F)
val DarkOnBackground = Color(0xFFE4E1E6)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE4E1E6)
val DarkSurfaceVariant = Color(0xFF46464F)
val DarkOnSurfaceVariant = Color(0xFFC7C5D0)
val DarkOutline = Color(0xFF91909A)

// Custom App-Specific Colors
val SuccessGreen = Color(0xFF4CAF50)
val ErrorRed = Color(0xFFF44336)
val HolidayYellow = Color(0xFFFFC107)
