package com.ankit.smartattendance.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Sage & Mint Palette
val LightPrimary = Color(0xFF3A6A5D)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBDEEE1)
val LightOnPrimaryContainer = Color(0xFF00201A)
val LightSecondary = Color(0xFF4A635D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE8E0)
val LightOnSecondaryContainer = Color(0xFF06201A)
val LightTertiary = Color(0xFF426277)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC7E7FF)
val LightOnTertiaryContainer = Color(0xFF001E2E)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBF7)
val LightOnBackground = Color(0xFF171D1B)
val LightSurface = Color(0xFFF4FBF7)
val LightOnSurface = Color(0xFF171D1B)
val LightSurfaceVariant = Color(0xFFDBE5E0)
val LightOnSurfaceVariant = Color(0xFF3F4945)
val LightOutline = Color(0xFF6F7975)

// Dark Theme - Sage & Mint Palette
val DarkPrimary = Color(0xFFA1D1C5)
val DarkOnPrimary = Color(0xFF02372E)
val DarkPrimaryContainer = Color(0xFF205146)
val DarkOnPrimaryContainer = Color(0xFFBDEEE1)
val DarkSecondary = Color(0xFFB1CCC4)
val DarkOnSecondary = Color(0xFF1D352F)
val DarkSecondaryContainer = Color(0xFF334B45)
val DarkOnSecondaryContainer = Color(0xFFCDE8E0)
val DarkTertiary = Color(0xFFAACBE1)
val DarkOnTertiary = Color(0xFF103345)
val DarkTertiaryContainer = Color(0xFF2A4A5D)
val DarkOnTertiaryContainer = Color(0xFFC7E7FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF101413)
val DarkOnBackground = Color(0xFFDFE4E1)
val DarkSurface = Color(0xFF101413)
val DarkOnSurface = Color(0xFFDFE4E1)
val DarkSurfaceVariant = Color(0xFF3F4945)
val DarkOnSurfaceVariant = Color(0xFFBEC9C4)
val DarkOutline = Color(0xFF89938F)


// Custom App-Specific Colors (Unchanged)
val SuccessGreen = Color(0xFF2E7D32)
val ErrorRed = Color(0xFFD32F2F)
val HolidayYellow = Color(0xFFFFA000)
